model_name_or_path: ../SFT/Model/SALV-SFT 
trust_remote_code: true

### method
stage: dpo
do_train: true
finetuning_type: lora

lora_target: all
pref_beta: 0.1
pref_loss: sigmoid  # choices: [sigmoid (dpo), orpo, simpo]

### dataset
dataset: SALV_SA_DPO_Data,SALV_SA_DPO_Data_Spec
template: qwen
cutoff_len: 2048
max_samples: 800000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: ../SA-DPO/Model/SALV-SA-DPO
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 5.0e-6
num_train_epochs: 2.0
max_steps: 7000
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500
